# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  unit_test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies and test with pytest
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r app/requirements.txt
            pytest --cov=app

  build:
    docker:
      - image: jdrouet/docker-with-buildx:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: default
          docker_layer_caching: true
      - run: |
          docker buildx build  --platform linux/arm64,linux/amd64  --tag ahmadalsajid/fast-app:dev ./app/


workflows:
  build_and_deploy:
    jobs:
      - unit_test
      - build:
          requires:
            - unit_test