# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

base_image: &base_image
  docker:
    - image: python:3.10-slim

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  unit_test:
    <<: *base_image
    steps:
      - checkout
      - run:
          name: Install dependencies and test with pytest
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r app/requirements.txt
            pytest --cov=app

  build:
    docker:
      - image: ahmadalsajid/docker-with-buildx:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: default
          docker_layer_caching: true
      - run:
          name: Get latest git tag and increase SemVer
          command: |
            chmod +x /tagging/git_tagging.sh 
            ./tagging/git_tagging.sh -v patch >> $BASH_ENV
      - run:
          name: docker login
          command: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_TOKEN"
      - run:
          name: build docker image and push to docker hub
          command: |
            docker buildx create --use
            if [ $BRANCH_NAME = main ]; then
              docker buildx build --push --platform linux/arm64,linux/amd64 --tag "$IMAGE_NAME":latest --tag "$IMAGE_NAME":"$git_tag" ./app/
            else
              docker buildx build --push --platform linux/arm64,linux/amd64  --tag "$IMAGE_NAME":dev --tag "$IMAGE_NAME":"$git_tag"-dev ./app/
            fi
    environment:
      IMAGE_NAME: ahmadalsajid/fast-app
      BRANCH_NAME: << pipeline.git.branch >>

workflows:
  build_and_deploy:
    jobs:
      - unit_test
      - build:
          context: fastappcci_<< pipeline.git.branch >>
          filters:
            branches:
              only:
                - main
                - dev
          requires:
            - unit_test
